--- #YAML:1.0
name: Template-Plugin-ShellQuote
version: 1.2
license: perl
distribution_type: module
requires:
  String::ShellQuote: 0
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Template::Plugin::ShellQuote:
    file: lib/Template/Plugin/ShellQuote.pm
    version: 1.2
generated_by: Module::Build version 0.20
